//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalStrength.Wpf.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SignalStrength.Wpf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignalStrength App for tracking WiFi strangth..
        /// </summary>
        public static string AbotDescription1 {
            get {
                return ResourceManager.GetString("AbotDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignalStrength App is open source code and you can check source code !.
        /// </summary>
        public static string AbotDescription2 {
            get {
                return ResourceManager.GetString("AbotDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstract.
        /// </summary>
        public static string AbstractTheme {
            get {
                return ResourceManager.GetString("AbstractTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string AppearanceSettingName {
            get {
                return ResourceManager.GetString("AppearanceSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal Strength.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WiFi-Signal Strength.
        /// </summary>
        public static string AppNameWifi {
            get {
                return ResourceManager.GetString("AppNameWifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Band:.
        /// </summary>
        public static string C2DBand {
            get {
                return ResourceManager.GetString("C2DBand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CH:.
        /// </summary>
        public static string C2DChannal {
            get {
                return ResourceManager.GetString("C2DChannal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength:.
        /// </summary>
        public static string C2DStrength {
            get {
                return ResourceManager.GetString("C2DStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time:.
        /// </summary>
        public static string C2DTime {
            get {
                return ResourceManager.GetString("C2DTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose how much channals rows to show in 3D chart!.
        /// </summary>
        public static string Channal3DSettingContent {
            get {
                return ResourceManager.GetString("Channal3DSettingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channal 3D Setting.
        /// </summary>
        public static string Channal3DSettingName {
            get {
                return ResourceManager.GetString("Channal3DSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channals.
        /// </summary>
        public static string Channals {
            get {
                return ResourceManager.GetString("Channals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.4 GHz Channals.
        /// </summary>
        public static string Channals24 {
            get {
                return ResourceManager.GetString("Channals24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channals heatmap.
        /// </summary>
        public static string ChannalsHeatmapName {
            get {
                return ResourceManager.GetString("ChannalsHeatmapName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose range how much to show in 2D networks chart!.
        /// </summary>
        public static string Chart2DSettingContent {
            get {
                return ResourceManager.GetString("Chart2DSettingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart 2D Setting.
        /// </summary>
        public static string Chart2DSettingName {
            get {
                return ResourceManager.GetString("Chart2DSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts.
        /// </summary>
        public static string Charts {
            get {
                return ResourceManager.GetString("Charts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProgramingFactory©.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string DarkTheme {
            get {
                return ResourceManager.GetString("DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap en {
            get {
                object obj = ResourceManager.GetObject("en", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap en_US {
            get {
                object obj = ResourceManager.GetObject("en_US", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size:.
        /// </summary>
        public static string FontSizeSettingName {
            get {
                return ResourceManager.GetString("FontSizeSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gauge.
        /// </summary>
        public static string Gauge {
            get {
                return ResourceManager.GetString("Gauge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hr_HR {
            get {
                object obj = ResourceManager.GetObject("hr-HR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensity.
        /// </summary>
        public static string IntensityCbtContent {
            get {
                return ResourceManager.GetString("IntensityCbtContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your language!.
        /// </summary>
        public static string LanguageSettingsContent {
            get {
                return ResourceManager.GetString("LanguageSettingsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to restart app after change language!.
        /// </summary>
        public static string LanguageSettingsContent2 {
            get {
                return ResourceManager.GetString("LanguageSettingsContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large.
        /// </summary>
        public static string LargeFont {
            get {
                return ResourceManager.GetString("LargeFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend.
        /// </summary>
        public static string Legend {
            get {
                return ResourceManager.GetString("Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string LegendBack {
            get {
                return ResourceManager.GetString("LegendBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D Channal Legend.
        /// </summary>
        public static string LegendContentTitle {
            get {
                return ResourceManager.GetString("LegendContentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crowd value.
        /// </summary>
        public static string LegendCrowdValue {
            get {
                return ResourceManager.GetString("LegendCrowdValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... and.
        /// </summary>
        public static string LegendCube1 {
            get {
                return ResourceManager.GetString("LegendCube1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cube.
        /// </summary>
        public static string LegendCube2 {
            get {
                return ResourceManager.GetString("LegendCube2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in bottom-right corner !.
        /// </summary>
        public static string LegendCube3 {
            get {
                return ResourceManager.GetString("LegendCube3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        public static string LegendDown {
            get {
                return ResourceManager.GetString("LegendDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No value.
        /// </summary>
        public static string LegendEmptyValue {
            get {
                return ResourceManager.GetString("LegendEmptyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra crowd value.
        /// </summary>
        public static string LegendExtraCrowdValue {
            get {
                return ResourceManager.GetString("LegendExtraCrowdValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front.
        /// </summary>
        public static string LegendFront {
            get {
                return ResourceManager.GetString("LegendFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string LegendLeft {
            get {
                return ResourceManager.GetString("LegendLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse Double Click.
        /// </summary>
        public static string LegendMouseDoubleClick {
            get {
                return ResourceManager.GetString("LegendMouseDoubleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse Left Click.
        /// </summary>
        public static string LegendMouseLeftClick {
            get {
                return ResourceManager.GetString("LegendMouseLeftClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse Right Click.
        /// </summary>
        public static string LegendMouseRightClick {
            get {
                return ResourceManager.GetString("LegendMouseRightClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse Weeel.
        /// </summary>
        public static string LegendMouseWeeel {
            get {
                return ResourceManager.GetString("LegendMouseWeeel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For navigate in 3D channal chart use.
        /// </summary>
        public static string LegendNavigate {
            get {
                return ResourceManager.GetString("LegendNavigate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pan.
        /// </summary>
        public static string LegendPan {
            get {
                return ResourceManager.GetString("LegendPan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string LegendRight {
            get {
                return ResourceManager.GetString("LegendRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate.
        /// </summary>
        public static string LegendRotate {
            get {
                return ResourceManager.GetString("LegendRotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set view to default.
        /// </summary>
        public static string LegendSetView {
            get {
                return ResourceManager.GetString("LegendSetView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single value.
        /// </summary>
        public static string LegendSingleValue {
            get {
                return ResourceManager.GetString("LegendSingleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three values.
        /// </summary>
        public static string LegendThreeValue {
            get {
                return ResourceManager.GetString("LegendThreeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two values.
        /// </summary>
        public static string LegendTwoValue {
            get {
                return ResourceManager.GetString("LegendTwoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        public static string LegendUp {
            get {
                return ResourceManager.GetString("LegendUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        public static string LegendZoom {
            get {
                return ResourceManager.GetString("LegendZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string LightTheme {
            get {
                return ResourceManager.GetString("LightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Networks.
        /// </summary>
        public static string Networks {
            get {
                return ResourceManager.GetString("Networks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wi-Fi not connected ....
        /// </summary>
        public static string NotConnectedText1 {
            get {
                return ResourceManager.GetString("NotConnectedText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignalStrengt app need Wi-Fi connection to work ....
        /// </summary>
        public static string NotConnectedText2 {
            get {
                return ResourceManager.GetString("NotConnectedText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palette:.
        /// </summary>
        public static string PaletteSettingName {
            get {
                return ResourceManager.GetString("PaletteSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        public static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wont to reset settings to default values ?.
        /// </summary>
        public static string ResetDialogContent {
            get {
                return ResourceManager.GetString("ResetDialogContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Settings ?.
        /// </summary>
        public static string ResetDialogTitle {
            get {
                return ResourceManager.GetString("ResetDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We did not touch the Settings ! .
        /// </summary>
        public static string ResetMessageCancel1 {
            get {
                return ResourceManager.GetString("ResetMessageCancel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings remained the same !.
        /// </summary>
        public static string ResetMessageCancel2 {
            get {
                return ResourceManager.GetString("ResetMessageCancel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings are set to default values !.
        /// </summary>
        public static string ResetMessageOK {
            get {
                return ResourceManager.GetString("ResetMessageOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset settings to default values.
        /// </summary>
        public static string ResetSettingContent {
            get {
                return ResourceManager.GetString("ResetSettingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Settings To Default.
        /// </summary>
        public static string ResetSettingName {
            get {
                return ResourceManager.GetString("ResetSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If app is slow try reset settings to default values !.
        /// </summary>
        public static string RestartSettingsBtnTooltip {
            get {
                return ResourceManager.GetString("RestartSettingsBtnTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart application.
        /// </summary>
        public static string RestartTooltip {
            get {
                return ResourceManager.GetString("RestartTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows.
        /// </summary>
        public static string Rows {
            get {
                return ResourceManager.GetString("Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning For Networks.
        /// </summary>
        public static string Scanning4Networks {
            get {
                return ResourceManager.GetString("Scanning4Networks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Interval.
        /// </summary>
        public static string ScanSettingInterval {
            get {
                return ResourceManager.GetString("ScanSettingInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Settings.
        /// </summary>
        public static string ScanSettingName {
            get {
                return ResourceManager.GetString("ScanSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fast.
        /// </summary>
        public static string ScanSettingSliderFast {
            get {
                return ResourceManager.GetString("ScanSettingSliderFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set networks scan interval.
        /// </summary>
        public static string ScanSettingSliderMainContent {
            get {
                return ResourceManager.GetString("ScanSettingSliderMainContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to slow.
        /// </summary>
        public static string ScanSettingSliderSlow {
            get {
                return ResourceManager.GetString("ScanSettingSliderSlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        public static string SmallFont {
            get {
                return ResourceManager.GetString("SmallFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snowflakes.
        /// </summary>
        public static string SnowflakesTheme {
            get {
                return ResourceManager.GetString("SnowflakesTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WiFi-Signal Strength app scanning networks ....
        /// </summary>
        public static string SplashMainText1 {
            get {
                return ResourceManager.GetString("SplashMainText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In meanwhile feel free to explore further ....
        /// </summary>
        public static string SplashMainText2 {
            get {
                return ResourceManager.GetString("SplashMainText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [It takes 10 seconds for the scan to accumulate(change in settings)].
        /// </summary>
        public static string SplashSecText1 {
            get {
                return ResourceManager.GetString("SplashSecText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [by ProgramingFactory©].
        /// </summary>
        public static string SplashSecText2 {
            get {
                return ResourceManager.GetString("SplashSecText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        public static string SSDCH {
            get {
                return ResourceManager.GetString("SSDCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        public static string SSDFrequency {
            get {
                return ResourceManager.GetString("SSDFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinkQuality.
        /// </summary>
        public static string SSDLinkQuality {
            get {
                return ResourceManager.GetString("SSDLinkQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MacAddress.
        /// </summary>
        public static string SSDMAC {
            get {
                return ResourceManager.GetString("SSDMAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SSDName {
            get {
                return ResourceManager.GetString("SSDName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NetBand.
        /// </summary>
        public static string SSDNetBand {
            get {
                return ResourceManager.GetString("SSDNetBand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignalStrength.
        /// </summary>
        public static string SSDSignalQuality {
            get {
                return ResourceManager.GetString("SSDSignalQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks.
        /// </summary>
        public static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks to all people behind open source libraries in Licence file.
        /// </summary>
        public static string ThanksContent {
            get {
                return ResourceManager.GetString("ThanksContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme:.
        /// </summary>
        public static string ThemeSettingName {
            get {
                return ResourceManager.GetString("ThemeSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Appearance.
        /// </summary>
        public static string VisualSettingName {
            get {
                return ResourceManager.GetString("VisualSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap wifi2 {
            get {
                object obj = ResourceManager.GetObject("wifi2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows phone.
        /// </summary>
        public static string WindowsPhone {
            get {
                return ResourceManager.GetString("WindowsPhone", resourceCulture);
            }
        }
    }
}
